### ISSUE TITLE
Lives are drawn on too lower of a layer.

### ISSUE THREAD

**Issue by dummey** [dummey/CS50-Cohort-Project-Redux#15]
Code is in: CS50-Cohort-Project-Redux/lib/game_objects/game_hud.rb

Where `@lives_icon.draw` occurs. A higher z index needs to be used.

The docs for `draw` are here: https://www.libgosu.org/rdoc/Gosu/Image.html#draw

**Comment by emeraldvision** [comment]
I seems like this has been fixed?

**Comment by dummey** [comment]
Yup @LucySchroeder pushed the changes last night.
