### ISSUE TITLE
fix asteroid logic for edges and corners

### ISSUE THREAD

**Issue by emeraldvision** [dummey/CS50-Cohort-Project-Redux#19]
For more details see #10 and #11 

Depends on #29, and can be done now with just an inherited module `DrawHelper`
- [ ] `require 'game_objects/role/draw_helper'`
- [ ] `include DrawHelper`
- [ ] add `:z_index = 1,` to _defaults`
- [ ] change `@asteroid_image` to `@image`
- [ ] change contents of `draw` method to `self.draw_with_boundary`

**Comment by jbtule** [comment]
@dummey fixed this in commits c4a96f9fee1994f19ca2e30651899a4dc5e37b3f 18a9f7e31df2ff0291f4cf8a74cca1a8809af685 42a78e0b0fbf16af12ad0831a6f5aed35b40625a
