### ISSUE TITLE
Enhance collision detection performance by moving shapes into different layers

### ISSUE THREAD

**Issue by jbtule** [dummey/CS50-Cohort-Project-Redux#21]
We should put [shapes](http://beoran.github.io/chipmunk/#Shape) in the the bit mask layers so it doesn't spend the effort for calculating collisions when we don't care.
- player hits UFO & asteroid
- laser beam hits UFO & asteroid

So Player: 1 (`0b01`) 
Laser_beam: 2 (`0b10`) 
 UFO & Asteriod: 3 (`0b11`),

**Comment by jbtule** [comment]
depends on issue #17

**Comment by emeraldvision** [comment]
I think UFOs should collide into asteroids, killing the UFO and breaking the asteroid into smaller pieces (similar to player).

**Comment by jbtule** [comment]
@dummey  completed this issue in commit  fb5a833430c0f5ea58b186b279640c889d2f1374
