### ISSUE TITLE
Player collide with fast moving UFOs causes Ship to spin on respawn

### ISSUE THREAD

**Issue by jbtule** [dummey/CS50-Cohort-Project-Redux#23]
This appears to occur every time now with the new fast moving baby ufo's. It's not just subtle movement, the player continues to fight it's own spin with left and right arrow for a bit even!

I'm assigning to ricky, because this is a perplexing mystery!

**Comment by dummey** [comment]
The problem occurs because of race conditions between the collision
    callback and the update loop. The reset was being called before
    the update which was doing collision based calculations. Thus
    momentum was being transferred between the ufo and player after
    reset.

**Comment by jbtule** [comment]
:+1:
