### ISSUE TITLE
Switch Player universe wrap around detection to using chipmunk sensor shapes

### ISSUE THREAD

**Issue by jbtule** [dummey/CS50-Cohort-Project-Redux#8]
To give the appearance of the ship universe wrapping around, a ghost ship image is drawn on the opposite side when the center point of the ship is within in image size / 2 of the border. 

The current code:

``` ruby
 # draw wrap around
 if (@body.p.x < @image.width / 2)
    @image.draw_rot(@scene.width + @body.p.x, @body.p.y, 1, @body.a.radians_to_gosu)
 elsif (@body.p.x > @scene.width + @image.width / 2)
   @image.draw_rot(@body.p.x - @scene.width, @body.p.y, 1, @body.a.radians_to_gosu)
 elsif (@body.p.y < @image.height / 2)
   @image.draw_rot(@body.p.x, @scene.height + @body.p.y, 1, @body.a.radians_to_gosu)
 elsif (@body.p.y > @scene.height + @image.height / 2)
   @image.draw_rot(@body.p.x, @body.p.y - @scene.height, 1, @body.a.radians_to_gosu)
 end
```

While this works fine, this could be refactored this to use [Chipmunk Shapes](http://beoran.github.io/chipmunk/#Shape) and a good way to learn how chipmunk shapes collision detection works.

To accomplish this:
- [x] Add a circle @shape ivar to player (constructor for shape is `CP::Shape::Circle.new(body, radius, offset)`)
- [x] Set collision_type of shape to a symbol for player, e.g. `:player`)`
- [x] Add player shape to space instead of body 
- [x] Add 4 line segment sensor shapes to the game scene to mark the Left, Top, Right and Bottom boundries of the universe.  (constructor is `CP::Shape::Segment.new(body, veca, vecb, radius)`) 
- [x] set property `sensor=true` so that these borders don't cause physical collisions.
- [x]  Set collision_type of shape to a symbol for each side
- [x]  In player, register collision collision handler to trigger drawing the ghost image of the ship (see example below) for each type

``` ruby
  #inner class defined yourself
  class CollisionHandler
    def begin(a, b, arbiter)
         #do something
    end

    def pre_solve(a, b)
       #ignored for sensor collisions
    end

    def post_solve(arbiter)
      #ignored for sensor collisions
    end

    def separate
       #do something
    end
  end
   #register handler for left_boundry example
   @space.add_collision_handler(:player, :left_boundry, CollisionHandler.new)
```

<img width="725" alt="Sensor Diagram" src="https://cloud.githubusercontent.com/assets/68474/8895814/2fb3b1ea-33ac-11e5-8976-61bd99fd9ef6.png">

**Comment by jbtule** [comment]
for @emeraldvision

**Comment by dummey** [comment]
:+1:
