### ISSUE TITLE
create logic for player invulnerability

### ISSUE THREAD

**Issue by emeraldvision** [dummey/CS50-Cohort-Project-Redux#9]
invulnerable for [x] seconds upon start and when respawning after death. should blink/be transparent to indicate invulnerability.

**Comment by jbtule** [comment]
depends on issue #21
- [x] Ship gets timestamp on `initialize`sets ivar
- [x] ship gets is_invulerable boolean ivar set to false
- [x] timestamp updated on `reset`
- [x] in update
  - [x] if `not is_invulerable` and timestamp is < x seconds then sets shape layer to 16 (`0b10000`) and set `is_invulerable = true`
  - [x] if `is_invulerable` and timestamp is > x seconds then set set shape layer to 1 (`0b01`) and set `is_invulerable = false`
  - [x] in draw, just draw transparent if  `is_invulerable`

**Comment by emeraldvision** [comment]
Grammatically "not invulnerable" bothers me... But I see the advantage of using "invulnerable" rather than "vulnerable" so that the default is false.

**Comment by jbtule** [comment]
:+1

**Comment by jbtule** [comment]
:+1:
